### ISSUE TITLE
libnss3 does not contain libsmime3.so

### ISSUE THREAD

**Issue by tri-bao** [canonical/chisel-releases#381]
In file `libnss3.yaml` (both 22.04 and 24.04), the libs slice only take `libnss3.so` and `libnssutil3.so`. But the package `libnss3` contains many other .so files [https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/libnss3_3.68.2-0ubuntu1_amd64.deb.html](https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/libnss3_3.68.2-0ubuntu1_amd64.deb.html)

One of them is `libsmime3.so` which can only found in this package. We need it. How do you suggest to solve this case?

**Comment by rebornplusplus** [comment]
Hiya, thanks for raising the issue. Indeed, a package may not have a particular file in any of their slices due to the rationale of slicing -- _get only what you need_.

Ideally, you would add a new slice for the specified files or include them all in the `libs` slice. I have done both and raised #382 for 22.04. Feel free to raise a PR for 24.04! :)

**Comment by tri-bao** [comment]
@rebornplusplus the PR #382 has been merged. However, if I understand that slice correctly, it still doesn't not contain all the libs contains in the `libnss3` package as shown in [https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/libnss3_3.68.2-0ubuntu1_amd64.deb.html](https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/libnss3_3.68.2-0ubuntu1_amd64.deb.html)

The PR only adds `libsmime3.so`. Now if I use the `libs` slice, I can only have 3 `.so`

```
      /usr/lib/*-linux-*/libnss3.so:
      /usr/lib/*-linux-*/libnssutil3.so:
      /usr/lib/*-linux-*/libsmime3.so:
``

The following are still missing (there's `libssl3.so` a slice for it exists)

``
      /usr/lib/*-linux-*/libfreebl3.so:
      /usr/lib/*-linux-*/libfreeblpriv3.so:
      /usr/lib/*-linux-*/nss/libfreebl3.so:
      /usr/lib/*-linux-*/nss/libfreeblpriv3.so:
      /usr/lib/*-linux-*/nss/libnssckbi.so:
      /usr/lib/*-linux-*/nss/libnssdbm3.so:
      /usr/lib/*-linux-*/nss/libsoftokn3.so:
``

Before the PR was merged, I created  a custom slice file `libnss3.yaml` overriding the chisel-releases' one (chisel tool does not allow different slices contain any same file). In the custom file, I add all `.so` to the libs slice. Now this PR is merged, which changed the  ca-certificates-java_data slice. Now I got following error `ca-certificates-java_data requires libnss3_nss, but slice is missing`

I understand the error. Because I don't define `nss` slice in my file. I can add it like in your slice file. However, would you advice me the correct away to handle this situation in which the upstream official slices doesn't contain the `.so` we need. Is there a way we can do in our custom slice so that our build won't be broken like this case. Furthermore, one day, the upstream may create new slice for `libfreebl3.so` (for example), then our build will be broken again because the chisel tool doesn't  allow different slice files contains the same file in section `contents`.

**Comment by tri-bao** [comment]
hi @rebornplusplus 

I'm heading back to this issue as I want to contribute but I am not clear about the contribution model.

For existing package files, my understanding from your above message is that: the only way to contribute is adding slices that I need. However, how granularity the slice should be? If I want just a single .so file, will I able to add a new single-lib slice?

I can give a more obvious example: the `libc6.yaml` in the chiseled-releases ignore all the encoding conversion `.so` and configuration files under folder `/usr/lib/x86_64-linux-gnu/gconv`. There are 253 encoding so I can understand why they are not part of any slice. The problem is I want a few of encoding, can I contribute a slice, then another person needs another permutation of these encoding, will the contribute another one, and so on so forth?

In this case, I would love to create my own package file with a slice containing only encoding that I need. However, chisel doesn't allow different file names for one package: if the package is libc6, the file must be `libc6.yaml`. I can't create a new file like `libc6-custom-encoding.yaml`

For packages that do not exist in chiseled-releases? How can I contribute them? In my project, a lot of them are missing. I currently have 82 packages defined in my own repo. Again, how granularity of slices in new packages is acceptable?

**Comment by cjdcordeiro** [comment]
Hi @tri-bao 

We'll be adding more explanatory guides about this soon. 
In the meantime:

> how granularity the slice should be? If I want just a single .so file, will I able to add a new single-lib slice?

We recommend sticking with the bare minimum for your use case to function properly. 
Keep in mind that comprehensive slice names like `libs`, `bins` ... usually comprise all the files of those types. So when being granular, we recommend creating a dedicated slice for the file(s) you are slicing. 

A good example is our Python3 slices, where, even though most files are Python modules, we decided to slice the packages by functionality.

> The problem is I want a few encoding, can I contribute a slice, then another person needs another permutation of these encoding, will that person contribute another one, and so on so forth?

You can create as many slices as needed. If your group of files has meaning, then name the slice after it. Another, very very granular approach, is what we've done with coreutils, where each binary gets its slice. 

> In this case, I would love to create my own package file with one slice containing only encoding that I need. However, chisel doesn't allow different file names for one package: if the package is libc6, the file must be libc6.yaml. I can't create a new file like libc6-custom-encoding.yaml

Indeed. it must all be within the same Slice Definitions File. But that's ok, because there's no limit to the number of slices you can have.

> For packages that do not exist in chiseled-releases? How can I contribute them?

That's great! Just create the PRs, and for the more subjective slice designing cases, we'll help you out.

_note that we might take longer to get back to you during this holiday period ;)_

**Comment by tri-bao** [comment]
thanks @cjdcordeiro for the explanation. I'll close this topic
